### ISSUE TITLE
Create Simple Javascript Parser

### ISSUE THREAD

**Issue by nheyn** [progrium/sveltish#14]
In order to do the required "Moving the JS code" and "Adding to the JS code", the Javascript inside the <script /> tag must be parser. But it won't require a full ast, just one that tracks a few key parts. So a "Simple" lexer/parser can be used. The things it must track are:
- top level variable declarations
- top level function declarations
- top level "$: " labels
- inner variable assignments of top level variables

Side Note: I did look into both the "/js" package from the "parser" library that is used for html and the parser in esbuild, but they both seem like they are not a good fit for what required. The one from "parser" only does ES5.1 which is pre-ES2015, (i.e. it only works with such an old version of js that it can't even parse the svelte files being created). And esbuild's parser is in its "internal/" packages and has a lot of extra stuff we don't need (mainly for minifying).

**Comment by nheyn** [comment]
@progrium Just wanted to give a quick update on this one:

My initial version of the lexer was not handling comments correctly, so I had todo a bit of a rewrite. I finished that yesterday (it has been[ pushed to my fork](https://github.com/nheyn/sveltish/tree/progrium/sveltish%2314)) and have started adapting the parser. That should be done before the end of the day. Once it is finished I will start on #11, and like I said before that and #12 should be quick once this one is done, so I still hope to have them finished this week.

**Comment by progrium** [comment]
Excited! Thanks for the update
